Repository DusanStevic/ISA-MRS-TIM18, pull requests merged in 2019-05, with the labels that each got.

#10 Registrovani korisnici i prijatelji
  Skynet/src/main/java/com/tim18/skynet/controller/AuthenticationController.java
  Skynet/src/main/java/com/tim18/skynet/model/RegisteredUser.java
  Skynet/src/main/java/com/tim18/skynet/repository/RegularUserRepository.java
  Skynet/src/main/java/com/tim18/skynet/repository/UserRepository.java
  Skynet/src/main/java/com/tim18/skynet/service/RegularUserService.java
  Skynet/src/main/java/com/tim18/skynet/service/impl/RegularUserServiceImpl.java
  Skynet/src/main/resources/application.properties
  Skynet/src/main/resources/data.sql
  Skynet/src/main/resources/static/AirlineAdministrator.html
  Skynet/src/main/resources/static/RegisteredUser.html
  Skynet/src/main/resources/static/js/login.js
  Skynet/src/main/resources/static/user-home.html
Labels: enhancement

#14 updateRAC
  Skynet/src/main/java/com/tim18/skynet/controller/BranchController.java
  Skynet/src/main/java/com/tim18/skynet/controller/CarController.java
  Skynet/src/main/java/com/tim18/skynet/controller/RACController.java
  Skynet/src/main/java/com/tim18/skynet/dto/BranchDTO.java
  Skynet/src/main/java/com/tim18/skynet/dto/CarDTO.java
  Skynet/src/main/resources/application.properties
  Skynet/src/main/resources/static/branchInfo.html
  Skynet/src/main/resources/static/carInfo.html
  Skynet/src/main/resources/static/js/displayCompanies.js
  Skynet/src/main/resources/static/js/login.js
  Skynet/src/main/resources/static/js/racAdmin.js
  Skynet/src/main/resources/static/racAdmin-companiesDisplay.html
  Skynet/src/main/resources/static/racAdmin-home.html
  Skynet/src/main/resources/static/racAdmin-racProfile.html
Labels: enhancement

#22 refaktorizacija dodavanja prijatelja
  Skynet/src/main/java/com/tim18/skynet/model/FriendRequest.java
  Skynet/src/main/java/com/tim18/skynet/model/RegisteredUser.java
Labels: enhancement

#25 refaktorizacija pretrage leta zbog rezervacija
  .recommenders/index/http___download_eclipse_org_recommenders_models_neon_/_1.fdx
  .recommenders/index/http___download_eclipse_org_recommenders_models_neon_/_1.fnm
  .recommenders/index/http___download_eclipse_org_recommenders_models_neon_/_1.frq
  .recommenders/index/http___download_eclipse_org_recommenders_models_neon_/_1.nrm
  .recommenders/index/http___download_eclipse_org_recommenders_models_neon_/_1.prx
  .recommenders/index/http___download_eclipse_org_recommenders_models_neon_/_1.tii
  .recommenders/index/http___download_eclipse_org_recommenders_models_neon_/_1.tis
  .recommenders/index/http___download_eclipse_org_recommenders_models_neon_/segments.gen
  .recommenders/index/http___download_eclipse_org_recommenders_models_neon_/segments_1
  .recommenders/index/http___download_eclipse_org_recommenders_models_neon_/segments_2
  Skynet/src/main/java/com/tim18/skynet/controller/AirlineController.java
  Skynet/src/main/java/com/tim18/skynet/model/Flight.java
  Skynet/src/main/resources/application.properties
  Skynet/src/main/resources/static/js/RegisteredUser.js
Labels: bug

#29 Rezervacija leta bug
  RemoteSystemsTempFiles/.project
  Skynet/src/main/java/com/tim18/skynet/controller/AirlineController.java
  Skynet/src/main/java/com/tim18/skynet/dto/FlightBean.java
  Skynet/src/main/java/com/tim18/skynet/model/Airline.java
  Skynet/src/main/java/com/tim18/skynet/model/Flight.java
  Skynet/src/main/java/com/tim18/skynet/model/Seat.java
  Skynet/src/main/java/com/tim18/skynet/service/impl/SeatService.java
  Skynet/src/main/resources/application.properties
  Skynet/src/main/resources/static/js/AirlineAdministrator.js
Labels: improvement

#31 renderovanje leta za rezervaciju
  Skynet/src/main/resources/static/js/RegisteredUser.js
Labels: improvement

#32 otklanjanje buga na rezervaciji sedista
  Skynet/src/main/resources/static/RegisteredUser.html
  Skynet/src/main/resources/static/js/RegisteredUser.js
Labels: improvement

#33 sediste bug fix
  Skynet/src/main/resources/static/RegisteredUser.html
  Skynet/src/main/resources/static/js/RegisteredUser.js
Labels: bug

#36 ispravka bug-a na sedistima
  Skynet/src/main/resources/application.properties
  Skynet/src/main/resources/static/js/AirlineAdministrator.js
Labels: bug fix
